routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\PaymentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
Route::resource('product', ProductController::class);
Route::resource('order', OrderController::class);
Route::resource('user', UserController::class);
Route::resource('cart', CartController::class);

//Product
Route::get('/products/{id}', [ProductController::class, 'show']);

//Cart
Route::get('/cart', [CartController::class, 'index']);
Route::get('add-to-cart/{id}', [CartController::class, 'store'])->name('cart-add');
Route::patch('update-cart', [CartController::class, 'update'])->name('cart-update');
Route::delete('remove-from-cart', [CartController::class, 'remove'])->name('cart-remove');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout.index');
    Route::post('/checkout/order', [CheckoutController::class, 'placeOrder'])->name('checkout.place.order');

    
    //Payment
    Route::get('stripe', [PaymentController::class, 'index']);
    Route::post('create-checkout-session', [PaymentController::class, 'makePayment']);

});


Route::get('/confirmation', [PaymentController::class, 'paymentSuccess'])->name('checkout.confirm');

resources/views/cart.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h4>{{ __('Shopping Cart') }}</h4>

                @if (session('success'))
                    <div class="alert alert-success" role="alert">
                        {{ session('success') }}
                    </div>
                @endif



                @if (session('cart'))
                    <table id="cart" class="table table-hover table-condensed">
                        <thead>
                            <tr>
                                <th style="width:50%">Product</th>
                                <th style="width:10%">Price</th>
                                <th style="width:8%">Units</th>
                                <th style="width:22%" class="text-center">Subtotal</th>
                                <th style="width:10%"></th>
                            </tr>
                        </thead>
                        <tbody>

                            <?php $total = 0; ?>


                            @foreach (session('cart') as $id => $details)

                                <?php $total += $details['price'] * $details['units']; ?>

                                <tr>
                                    <td data-th="Product">
                                        <div class="row">
                                            <div class="col-sm-3 hidden-xs"><img src="{{ $details['photo'] }}" width="100"
                                                    height="100" class="img-responsive" /></div>
                                            <div class="col-sm-9">
                                                <h5 class="nomargin">{{ $details['name'] }}</h5>
                                                <p>{{ $details['description'] }}</p>
                                            </div>
                                        </div>
                                    </td>
                                    <td data-th="Price">${{ $details['price'] }}</td>
                                    <td data-th="units">
                                        <input type="number" value="{{ $details['units'] }}" class="form-control units" />
                                    </td>
                                    <td data-th="Subtotal" class="text-center">
                                        ${{ $details['price'] * $details['units'] }}</td>
                                    <td class="actions" data-th="">
                                        <button class="btn btn-info btn-sm update-cart" data-id="{{ $id }}"><svg
                                                xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                fill="currentColor" class="bi bi-recycle" viewBox="0 0 16 16">
                                                <path
                                                    d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z" />
                                            </svg></button>
                                        <button class="btn btn-danger btn-sm remove-from-cart"
                                            data-id="{{ $id }}"><svg xmlns="http://www.w3.org/2000/svg" width="16"
                                                height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                <path
                                                    d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                                <path fill-rule="evenodd"
                                                    d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                            </svg></button>
                                    </td>
                                </tr>
                            @endforeach


                        </tbody>
                        <tfoot>
                            <tr class="visible-xs">
                                <td colspan="3"></td>
                                <td class="text-center"><strong>Total {{ $total }}</strong></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td colspan="5"><a href="{{ url('/') }}" class="btn btn-warning"><i
                                            class="fa fa-angle-left"></i>
                                        Continue Shopping</a></td>

                            </tr>
                        </tfoot>
                    </table>
                    <div class="flex">
                        <a href="{{ route('checkout.index') }}" class="btn btn-success btn-lg btn-block">Proceed To
                            Checkout</a>
                    </div>
                @else
                    <div class="alert alert-warning" role="alert">
                        No items in cart.
                    </div>
                @endif


            </div>
        </div>
    </div>
@endsection

resources/views/checkout.blade.php
@extends('layouts.app')
@section('content')
    <?php $total = 0; ?>
    <section class="section-content bg padding-y">
        <div class="container">
            <h2>Checkout</h2>
            <div class="row">
                <div class="col-sm-12">
                    @if (Session::has('error'))
                        <p class="alert alert-danger">{{ Session::get('error') }}</p>
                    @endif
                </div>
            </div>

            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="#" id="checkout-form" method="POST" role="form">
                @csrf
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <header class="card-header">
                                <h4 class="card-title mt-2">Billing Details</h4>
                            </header>
                            <article class="card-body">
                                <div class="form-row">
                                    <div class="col form-group">
                                        <label>First name</label>
                                        <input type="text" class="form-control" name="first_name"
                                            value="{{ $user->first_name }}" required>
                                    </div>
                                    <div class="col form-group">
                                        <label>Last name</label>
                                        <input type="text" class="form-control" name="last_name" required
                                            value="{{ $user->first_name }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Address</label>
                                    <input type="text" class="form-control" name="address" required
                                        value="{{ $user->address }}">
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label>City</label>
                                        <input type="text" class="form-control" name="city" required
                                            value="{{ $user->city }}">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label>Country</label>
                                        <input type="text" class="form-control" name="country" required
                                            value="{{ $user->country }}">
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group  col-md-6">
                                        <label>Post Code</label>
                                        <input type="text" class="form-control" name="post_code" required
                                            value="{{ $user->post_code }}">
                                    </div>
                                    <div class="form-group  col-md-6">
                                        <label>Phone Number</label>
                                        <input type="text" class="form-control" name="phone_number" required
                                            value="{{ $user->phone_number }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Email Address</label>
                                    <input type="email" class="form-control" name="email"
                                        value="{{ auth()->user()->email }}" disabled>
                                    <small class="form-text text-muted">We'll never share your email with anyone
                                        else.</small>
                                </div>
                                <div class="form-group">
                                    <label>Order Notes</label>
                                    <textarea class="form-control" name="notes" rows="6"></textarea>
                                </div>
                            </article>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card">
                                    <header class="card-header">
                                        <h4 class="card-title mt-2">Your Order</h4>
                                    </header>
                                    <article class="card-body">
                                        <dl class="dlist-align">
                                            <dt>Total cost: </dt>
                                            <dd class="text-left h5 b">
                                                @if (session('cart'))
                                                    @foreach (session('cart') as $id => $details)

                                                        <?php $total += $details['price'] *
                                                        $details['units']; ?>

                                                    @endforeach
                                                @endif
                                                {{ config('app.currency') }} {{ $total }}
                                            </dd>
                                        </dl>
                                    </article>
                                </div>
                            </div>
                            <div class="col-md-12 mt-4">
                                <button type="submit" class="subscribe btn btn-success btn-lg btn-block">Place
                                    Order</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
@stop

resources/views/confirmation.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h4>{{ __('Payment Successful') }}</h4>

                @if (session('success'))
                    <div class="alert alert-success" role="alert">
                        {{ session('success') }}
                    </div>
                @endif


            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h4>{{ __('Catalog') }}</h4>

                @if (session('success'))
                    <div class="alert alert-success" role="alert">
                        {{ session('success') }}
                    </div>
                @endif

                <div class="row row-cols-1 row-cols-md-3 row-cols-lg-4">
                    @foreach ($products as $product)


                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                <img class="card-img-top" data-src="{{ $product->image }}" alt="Thumbnail [100%x225]"
                                    style="height: 225px; width: 100%; display: block;" src="{{ $product->image }}"
                                    data-holder-rendered="true">
                                <div class="card-body">
                                    <h5 class="card-title">{{ $product->name }}</h5>
                                    <p class="card-text">{{ $product->description }}<br />{{ config('app.currency') }}
                                        {{ $product->price }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a class="btn btn-sm btn-outline-secondary"
                                                href="{{ route('product.show', $product->id) }}">View</a>
                                            <a class="btn btn-sm btn-outline-secondary"
                                                href="{{ route('cart-add', $product->id) }}" role="button">Add to
                                                cart</a>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>

                    @endforeach

                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/product.blade.php
@extends('layouts.app') @section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session("success") }}
            </div>
            @endif
            <div class="row">
                <div class="col-md-5 text-center">
                    <img src="{{ $product->image }}" class="img-fluid" />
                </div>
                <div class="col-md-7">
                    <h4>{{ $product->name }}</h4>
                    <p>{{ $product->price }}</p>
                    <p>{{ $product->description }}</p>

                    <a
                        class="btn btn-primary"
                        href="{{ route('cart-add', $product->id) }}"
                        role="button"
                        >Add to cart</a
                    >
                </div>
            </div>
        </div>
    </div>
</div>
@endsection