routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\PaymentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
Route::resource('product', ProductController::class);
Route::resource('order', OrderController::class);
Route::resource('user', UserController::class);
Route::resource('cart', CartController::class);

//Product
Route::get('/products/{id}', [ProductController::class, 'show']);

//Cart
Route::get('/cart', [CartController::class, 'index']);
Route::get('add-to-cart/{id}', [CartController::class, 'store'])->name('cart-add');
Route::patch('update-cart', [CartController::class, 'update'])->name('cart-update');
Route::delete('remove-from-cart', [CartController::class, 'remove'])->name('cart-remove');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout.index');
    Route::post('/checkout/order', [CheckoutController::class, 'placeOrder'])->name('checkout.place.order');

    
    //Payment
    Route::get('stripe', [PaymentController::class, 'index']);
    Route::post('create-checkout-session', [PaymentController::class, 'makePayment']);

});


Route::get('/confirmation', [PaymentController::class, 'paymentSuccess'])->name('checkout.confirm');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Order extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'order_number', 'user_id', 'status', 'grand_total', 'item_count', 'payment_status', 'payment_method',
        'first_name', 'last_name', 'address', 'city', 'country', 'post_code', 'phone_number', 'notes'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }
    
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Order;
use App\Models\User;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Auth\SessionGuard;
use Illuminate\Support\Facades\Validator;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if( Auth::user()->is_admin ){
            return view('admin.orders.index')->with('orders', Order::with(['product'])->get());
        }else{
            return view('admin.orders.index')->with('orders', Order::where('user_id', '=', Auth::id())->get());
        }
        
    }


    public function deliverOrder(Order $order)
    {
        $order->is_delivered = true;
        $status = $order->save();

        return response()->json([
            'status'    => $status,
            'data'      => $order,
            'message'   => $status ? 'Order Delivered!' : 'Error Delivering Order'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    public function updateStatus($id){

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order = Order::create([
            'product_id' => $request->product_id,
            'user_id' => Auth::id(),
            'quantity' => $request->quantity,
            'address' => $request->address
        ]);

        return response()->json([
            'status' => (bool) $order,
            'data'   => $order,
            'message' => $order ? 'Order Created!' : 'Error Creating Order'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        return response()->json($order,200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('admin.orders.edit', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $status = $order->update(
            $request->only(['status'])
        );

        return redirect()->route('order.index')->with('status', $status)->with('message', $status ? 'Order Updated!' : 'Error Updating Order');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $status = $order->delete();

            return response()->json([
                'status' => $status,
                'message' => $status ? 'Order Deleted!' : 'Error Deleting Order'
            ]);
    }
}

resources/views/admin/orders/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Edit order</h2>
                </div>
                <div class="pull-right py-3">
                    <a class="btn btn-primary" href="{{ route('order.index') }}" title="Go back"> Go back </a>
                </div>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('order.update', $order->id) }}" method="POST">
            @csrf
            @method('PUT')

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <header class="card-header">
                            <h4 class="card-title mt-2">Order Details</h4>
                        </header>
                        <article class="card-body">

                            <div class="form-row">
                                <div class="col form-group">
                                    <label>Order Number</label>
                                    <p>{{ $order->order_number }}</p>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="col form-group">
                                    <label>Payment Status</label>
                                    <p>{{ $order->payment_status }}</p>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="col form-group">
                                    <label>Payment Method</label>
                                    <p>{{ $order->payment_method }}</p>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="col form-group">
                                    <label>Total Items</label>
                                    <p>{{ $order->item_count }}</p>
                                </div>
                            </div>




                            <div class="form-group">
                                <label>Order Status</label>
                                <select class="form-control" name="status">
                                    <option value="pending" @if ($order->status === 'pending') selected @endif>Payment Pending</option>
                                    <option value="processing" @if ($order->status === 'received') selected @endif>Payment Received</option>
                                    <option value="completed" @if ($order->status === 'completed') selected @endif>Completed</option>
                                    <option value="shipped" @if ($order->status === 'shipped') selected @endif>Shipped</option>
                                    <option value="decline" @if ($order->status === 'decline') selected @endif>Decline</option>
                                </select>
                            </div>


                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </article>
                    </div>
                </div>
            </div>


        </form>
    </div>
@endsection

resources/views/admin/orders/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.nav')
            <div class="col-md-10">

                @if ($message = Session::get('message'))
                    <div class="alert alert-success" role="alert">
                        {{ $message }}
                    </div>
                @endif

                <div class="d-flex justify-content-between mb-3">
                    <div>
                        <h4>Orders</h4>
                    </div>
                    <div>
                    </div>
                </div>

                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Order Number</th>
                            <th scope="col">Total Price</th>
                            <th scope="col">Order Status</th>
                            <th scope="col">Payment Status</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($orders as $order)
                            <tr>
                                <th scope="row">{{ $order->order_number }}</th>
                                <td>{{ $order->grand_total }}</td>
                                <td>
                                    {{ $order->status }}
                                </td>
                                <td>
                                    @if ($order->payment_status)
                                        Paid
                                    @else
                                        Waiting for payment
                                    @endif

                                </td>
                                <td>

                                    <a class="btn btn-primary btn-warning" href="/order/{{ $order->id }}/edit"
                                        role="button">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                            class="bi bi-pencil-square" viewBox="0 0 16 16">
                                            <path
                                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                            <path fill-rule="evenodd"
                                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                                        </svg>
                                    </a>

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>

    @endsection